HW03_u20679484/Models/authors.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW03_u20679484.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class authors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public authors()
        {
            this.books = new HashSet<books>();
        }
    
        public int authorId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<books> books { get; set; }
    }
}

HW03_u20679484/Controllers/MaintainController.cs
using HW03_u20679484.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace HW03_u20679484.Controllers
{
    public class MaintainController : Controller
    {
        private LibraryEntities db = new LibraryEntities();
        public async Task<ActionResult> MaintainIndex(int? authorPage, int? typePage, int? borrowPage)
        {
            int authorPageSize = 10;
            int authorPageNumber = authorPage ?? 1;

            var authors = await db.authors.ToListAsync();
            var pagedAuthors = authors.ToPagedList(authorPageNumber, authorPageSize);

            int typePageSize = 10;
            int typePageNumber = typePage ?? 1;

            var types = await db.types.ToListAsync();
            var pagedTypes = types.ToPagedList(typePageNumber, typePageSize);

            int borrowPageSize = 10;
            int borrowPageNumber = borrowPage ?? 1;

            var borrows = await db.borrows.ToListAsync();
            var pagedBorrows = borrows.ToPagedList(borrowPageNumber, borrowPageSize);

            var viewModel = new CombinedViewModel
            {
                Authors = pagedAuthors,
                Types = pagedTypes,
                Borrows = pagedBorrows
            };

            return View("MaintainIndex", viewModel);
        }

        // Action methods for Authors
        public async Task<ActionResult> AuthorIndex(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;

            var authors = await db.authors.ToListAsync();
            var pagedAuthors = authors.ToPagedList(pageNumber, pageSize);

            return View("AuthorIndex", pagedAuthors);
        }

        public async Task<ActionResult> AuthorDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            authors author = await db.authors.FindAsync(id);

            if (author == null)
            {
                return HttpNotFound();
            }

            return View(author);
        }

        public ActionResult AuthorCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AuthorCreate([Bind(Include = "name, surname")] authors author)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(author);
                await db.SaveChangesAsync();
                return RedirectToAction("AuthorIndex");
            }

            return View(author);
        }

        public async Task<ActionResult> AuthorEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            authors author = await db.authors.FindAsync(id);

            if (author == null)
            {
                return HttpNotFound();
            }

            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AuthorEdit([Bind(Include = "authorId, name, surname")] authors author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("AuthorIndex");
            }

            return View(author);
        }

        public async Task<ActionResult> AuthorDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            authors author = await db.authors.FindAsync(id);

            if (author == null)
            {
                return HttpNotFound();
            }

            return View(author);
        }

        [HttpPost, ActionName("AuthorDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AuthorDeleteConfirmed(int id)
        {
            authors author = await db.authors.FindAsync(id);
            db.authors.Remove(author);
            await db.SaveChangesAsync();
            return RedirectToAction("AuthorIndex");
        }

        // Action methods for Borrows
        public async Task<ActionResult> BorrowIndex(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;

            var borrows = await db.borrows.ToListAsync();
            var pagedBorrows = borrows.ToPagedList(pageNumber, pageSize);

            return View("BorrowIndex", pagedBorrows);
        }

        public async Task<ActionResult> BorrowDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            borrows borrow = await db.borrows.FindAsync(id);

            if (borrow == null)
            {
                return HttpNotFound();
            }

            return View(borrow);
        }

        public ActionResult BorrowCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BorrowCreate([Bind(Include = "studentId, bookId, takenDate, broughtDate")] borrows borrow)
        {
            if (ModelState.IsValid)
            {
                db.borrows.Add(borrow);
                await db.SaveChangesAsync();
                return RedirectToAction("BorrowIndex");
            }

            return View(borrow);
        }

        public async Task<ActionResult> BorrowEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            borrows borrow = await db.borrows.FindAsync(id);

            if (borrow == null)
            {
                return HttpNotFound();
            }

            return View(borrow);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BorrowEdit([Bind(Include = "borrowId, studentId, bookId, takenDate, broughtDate")] borrows borrow)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrow).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("BorrowIndex");
            }

            return View(borrow);
        }

        public async Task<ActionResult> BorrowDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            borrows borrow = await db.borrows.FindAsync(id);

            if (borrow == null)
            {
                return HttpNotFound();
            }

            return View(borrow);
        }

        [HttpPost, ActionName("BorrowDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BorrowDeleteConfirmed(int id)
        {
            borrows borrow = await db.borrows.FindAsync(id);
            db.borrows.Remove(borrow);
            await db.SaveChangesAsync();
            return RedirectToAction("BorrowIndex");
        }

        // Action methods for Types
        public async Task<ActionResult> TypeIndex(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;

            var types = await db.types.ToListAsync();
            var pagedTypes = types.ToPagedList(pageNumber, pageSize);

            return View("TypeIndex", pagedTypes);
        }

        public async Task<ActionResult> TypeDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            types type = await db.types.FindAsync(id);

            if (type == null)
            {
                return HttpNotFound();
            }

            return View(type);
        }

        public ActionResult TypeCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TypeCreate([Bind(Include = "name")] types type)
        {
            if (ModelState.IsValid)
            {
                db.types.Add(type);
                await db.SaveChangesAsync();
                return RedirectToAction("TypeIndex");
            }

            return View(type);
        }

        public async Task<ActionResult> TypeEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            types type = await db.types.FindAsync(id);

            if (type == null)
            {
                return HttpNotFound();
            }

            return View(type);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TypeEdit([Bind(Include = "typeId, name")] types type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(type).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("TypeIndex");
            }

            return View(type);
        }

        public async Task<ActionResult> TypeDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            types type = await db.types.FindAsync(id);

            if (type == null)
            {
                return HttpNotFound();
            }

            return View(type);
        }

        [HttpPost, ActionName("TypeDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> TypeDeleteConfirmed(int id)
        {

HW03_u20679484/Controllers/authorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03_u20679484.Models;

namespace HW03_u20679484.Controllers
{
    public class authorsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: authors
        public async Task<ActionResult> Index()
        {
            return View(await db.authors.ToListAsync());
        }

        // GET: authors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // GET: authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(authors);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(authors);
        }

        // GET: authors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authors).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(authors);
        }

        // GET: authors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            authors authors = await db.authors.FindAsync(id);
            db.authors.Remove(authors);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03_u20679484/Views/authors/Create.cshtml
@model HW03_u20679484.Models.authors

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>authors</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("MaintainIndex", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
            <input type="submit" value="Create" class="btn btn-danger btn-sm" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HW03_u20679484/Views/authors/Delete.cshtml
@model HW03_u20679484.Models.authors

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>authors</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surname)
        </dd>

    </dl>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
                <a href="@Url.Action("MaintainIndex", "Maintain")" class="btn btn-primary btn-sm">Cancel</a>
            </div>
        </div>
    }
</div>

HW03_u20679484/Views/authors/Details.cshtml
@model HW03_u20679484.Models.authors

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>authors</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surname)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("MaintainIndex", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
</p>

HW03_u20679484/Views/authors/Edit.cshtml
@model HW03_u20679484.Models.authors

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>authors</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.authorId)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("MaintainIndex", "Maintain")" class="btn btn-primary btn-sm">Back to List</a>
                <input type="submit" value="Save Changes" class="btn btn-danger btn-sm" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HW03_u20679484/Views/authors/Index.cshtml
@model IEnumerable<HW03_u20679484.Models.authors>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surname)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.authorId }) |
            @Html.ActionLink("Details", "Details", new { id=item.authorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.authorId })
        </td>
    </tr>
}

</table>