HW03_u20679484/Controllers/HomeController.cs
using HW03_u20679484.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace HW03_u20679484.Controllers
{
    public class HomeController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        public async Task<ActionResult> CombinedIndex(int? studentPage, int? bookPage)
        {
            int studentPageSize = 10;
            int studentPageNumber = (studentPage ?? 1);

            var students = await db.students.ToListAsync();
            var pagedStudents = students.ToPagedList(studentPageNumber, studentPageSize);

            int bookPageSize = 10;
            int bookPageNumber = (bookPage ?? 1);

            var books = await db.books.ToListAsync();
            var pagedBooks = books.ToPagedList(bookPageNumber, bookPageSize);

            var viewModel = new CombinedViewModel
            {
                Students = pagedStudents,
                Books = pagedBooks
            };

            return View(viewModel);
        }


        // Action methods for students
        public async Task<ActionResult> StudentIndex(int? page)
        {
            int pageSize = 10; // Set the number of items to display per page
            int pageNumber = (page ?? 1); // Get the current page number, or default to page 1 if no page is specified

            // Retrieve the list of students from the database
            var students = await db.students.ToListAsync();

            // Paginate the list of students
            var pagedStudents = students.ToPagedList(pageNumber, pageSize);

            return View("StudentIndex", pagedStudents);
        }


        public async Task<ActionResult> StudentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            students student = await db.students.FindAsync(id);

            if (student == null)
            {
                return HttpNotFound();
            }

            return View(student);
        }

        public ActionResult StudentCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentCreate([Bind(Include = "name, surname, birthdate, gender, class, point")] students student)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(student);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentIndex");
            }

            return View(student);
        }

        public async Task<ActionResult> StudentEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            students student = await db.students.FindAsync(id);

            if (student == null)
            {
                return HttpNotFound();
            }

            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentEdit([Bind(Include = "studentId, name, surname, birthdate, gender, class, point")] students student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentIndex");
            }

            return View(student);
        }

        public async Task<ActionResult> StudentDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            students student = await db.students.FindAsync(id);

            if (student == null)
            {
                return HttpNotFound();
            }

            return View(student);
        }

        [HttpPost, ActionName("StudentDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentDeleteConfirmed(int id)
        {
            students student = await db.students.FindAsync(id);
            db.students.Remove(student);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentIndex");
        }

        // Action methods for books
        public async Task<ActionResult> BookIndex(int? page)
        {
            int pageSize = 10; // Set the number of items to display per page
            int pageNumber = (page ?? 1); // Get the current page number, or default to page 1 if no page is specified

            // Retrieve the list of books from the database
            var books = await db.books.ToListAsync();

            // Paginate the list of books
            var pagedBooks = books.ToPagedList(pageNumber, pageSize);

            
            return View("BookIndex", pagedBooks);
        }


        public async Task<ActionResult> BookDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            books book = await db.books.FindAsync(id);

            if (book == null)
            {
                return HttpNotFound();
            }

            return View(book);
        }

        public ActionResult BookCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BookCreate([Bind(Include = "name, pagecount, point, authorId, typeId")] books book)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(book);
                await db.SaveChangesAsync();
                return RedirectToAction("BookIndex");
            }

            return View(book);
        }

        public async Task<ActionResult> BookEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            books book = await db.books.FindAsync(id);

            if (book == null)
            {
                return HttpNotFound();
            }

            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BookEdit([Bind(Include = "bookId, name, pagecount, point, authorId, typeId")] books book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("BookIndex");
            }

            return View(book);
        }

        public async Task<ActionResult> BookDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            books book = await db.books.FindAsync(id);

            if (book == null)
            {
                return HttpNotFound();
            }

            return View(book);
        }

        [HttpPost, ActionName("BookDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BookDeleteConfirmed(int id)
        {
            books book = await db.books.FindAsync(id);
            db.books.Remove(book);
            await db.SaveChangesAsync();
            return RedirectToAction("BookIndex");
        }
        public string GetBookStatus(int bookId)
        {
            var borrowRecord = db.borrows.FirstOrDefault(b => b.bookId == bookId && b.broughtDate == null);

            if (borrowRecord != null)
            {
                return "Out";
            }

            return "Available";
        }
    }
}

HW03_u20679484/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03_u20679484.Models;

namespace HW03_u20679484.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("CombinedIndex", "Home");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("CombinedIndex", "Home");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("CombinedIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03_u20679484/Controllers/studentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03_u20679484.Models;

namespace HW03_u20679484.Controllers
{
    public class studentsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: students
        public async Task<ActionResult> Index()
        {
            return View(await db.students.ToListAsync());
        }

        // GET: students/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // GET: students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("CombinedIndex", "Home");
            }

            return View(students);
        }

        // GET: students/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("CombinedIndex", "Home");
            }
            return View(students);
        }

        // GET: students/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            students students = await db.students.FindAsync(id);
            db.students.Remove(students);
            await db.SaveChangesAsync();
            return RedirectToAction("CombinedIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03_u20679484/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

HW03_u20679484/Views/Home/CombinedIndex.cshtml
@using PagedList
@using PagedList.Mvc

@model HW03_u20679484.Models.CombinedViewModel

@{
    ViewBag.Title = "CombinedIndex";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    table.table-striped-light-pink {
        border-collapse: collapse;
        width: 100%;
    }

        table.table-striped-light-pink th,
        table.table-striped-light-pink td {
            border: 1px solid #ffffff;
            padding: 8px;
            text-align: left;
        }

        table.table-striped-light-pink thead {
            background-color: #ffc0cb; /* Light pink header */
            color: #333;
        }

        table.table-striped-light-pink tbody tr:nth-child(odd) {
            background-color: #f9f9f9; /* Light gray zebra stripe odd rows */
        }

        table.table-striped-light-pink tbody tr:nth-child(even) {
            background-color: #e9e9e9; /* Light gray zebra stripe even rows */
        }

    /* Styles for the links */
    .create-link {
        color: #007BFF; /* Primary color for Create link */
    }

    .edit-link {
        color: #FFC107; /* Warning color for Edit link */
    }

    .delete-link {
        color: #DC3545; /* Danger color for Delete link */
    }

    .details-link {
        color: #17A2B8; /* Info color for Details link */
    }

    /* Style for pagination buttons */
    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        list-style: none;
    }

    .pagination li {
        margin: 0 5px;
    }

    .pagination a {
        display: block;
        padding: 5px 10px;
        background-color: #007BFF;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
    }

    .pagination a:hover {
        background-color: #0056b3;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <h2>Students</h2>

        <p>
            <a href="#" class="create-link btn btn-primary" data-url="@Url.Action("Create", "students")">Create New Student</a>
        </p>

        <table class="table table-striped-light-pink" style="width:100%">
            <!-- Display ToDoList data -->
            <tr>
                <th style="background-color:hotpink">
                    ID
                </th>
                <th style="background-color: hotpink">
                    Name
                </th>
                <th style="background-color: hotpink">
                    Surname
                </th>
                <th style="background-color: hotpink">
                    BirthDate
                </th>
                <th style="background-color: hotpink">
                    Gender

                </th>
                <th style="background-color: hotpink">
                    Class
                </th>
                <th style="background-color: hotpink">
                    Point
                </th>

            </tr>
            @foreach (var student in Model.Students)
            {
                <tr>
                    <td>
                        @student.studentId
                    </td>
                    <td>
                        @student.name
                    </td>
                    <td>
                        @student.surname
                    </td>
                    <td>
                        @student.birthdate
                    </td>
                    <td>
                        @student.gender
                    </td>
                    <td>@(student.@class)</td>

                    <td>
                        @student.point
                    </td>

                </tr>
            }
        </table>
        @Html.PagedListPager(
     Model.Students, // Pass the Students paged list
     page => Url.Action("CombinedIndex", new { studentPage = page }),
     new PagedListRenderOptions
     {
         Display = PagedListDisplayMode.IfNeeded,
         DisplayPageCountAndCurrentLocation = true,
         MaximumPageNumbersToDisplay = 5, // Adjust this as needed
     }
 )
    </div>
    <div class="col-md-12">
        <h2>Books</h2>

        <p>
            <a href="#" class="create-link btn btn-primary" data-url="@Url.Action("Create", "books")">Create New Book</a>
        </p>

        <table class="table table-striped-light-pink" style="width:100%"">
            <!-- Display ListItem data -->
            <tr>
                <th style="background-color: hotpink">
                    ID
                </th>
                <th style="background-color: hotpink">
                    Name
                </th>
                <th style="background-color: hotpink">
                    Pagecount
                </th>
                <th style="background-color: hotpink">
                    Point
                </th>
                <th style="background-color:hotpink">
                    Status
                </th>

            </tr>
            @foreach (var books in Model.Books)
            {
                <tr>
                    <td>
                        @books.bookId
                    </td>
                    <td>
                        @books.name
                    </td>
                    <td>
                        @books.pagecount
                    </td>
                    <td>
                        @books.point
                    </td>
                    <td>
                        <span id="status-@books.bookId">Calculating...</span>
                     
                    </td>
                </tr>
            }
        </table>
        @Html.PagedListPager(
       Model.Books, // Replace this with the actual collection you want to paginate for books
       page => Url.Action("CombinedIndex", new { bookPage= page }),
       new PagedListRenderOptions
       {
           Display = PagedListDisplayMode.IfNeeded,
           DisplayPageCountAndCurrentLocation = true,
           MaximumPageNumbersToDisplay = 5, // Adjust this as needed

       }
   )
    </div>

</div>
<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> Async CRUD</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-content">
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"></script>
<script>

        // JavaScript to fetch and update book status asynchronously
        $(document).ready(function () {
            // Function to get book status and update UI
            function updateBookStatus(bookId) {
                $.get("/Home/GetBookStatus?bookId=" + bookId, function (status) {
                    $("#status-" + bookId).text(status);
                });
            }

            // Iterate through each book and update its status
            @foreach (var book in Model.Books)
            {
                <text>updateBookStatus(@book.bookId);</text>
            }
        });
    $(function () {
        // Function to handle Edit link click event in the Combined View and Details modal
        $(".edit-link, .edit-link-in-modal").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });

        // Function to handle form submission within the modal
        $("#modal-content").on("submit", "form", function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr("action");
            var formData = form.serialize();

            $.post(url, formData, function (data) {
                $("#myModal").modal("hide");
                location.reload();
            });
        });

        // Function to handle other links (details, delete, create) within the modal
        $(".details-link, .delete-link, .create-link, .create-lookup-link").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });
    });
</script>

HW03_u20679484/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

HW03_u20679484/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>