HW03_u20679484/Models/BorrowReport.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace HW03_u20679484.Models
{
    public class BorrowReport
    {
        public List<StudentMonthlyBorrow> GetStudentMonthlyBorrows(int studentId)
        {
            using (var context = new LibraryEntities())
            {
                var query = from b in context.borrows
                            where b.studentId == studentId
                            group b by new
                            {
                                Month = b.takenDate,
                            } into g
                            select new
                            {
                                g.Key.Month,
                                Count = g.Count()
                            };

                var reportData = query.ToList() // Retrieve the data from the database
                    .Select(item => new StudentMonthlyBorrow
                    {
                        Month = item.Month.HasValue
                            ? $"{item.Month.Value.Month:D2}/{item.Month.Value.Year}"
                            : "N/A",
                        BooksBorrowed = item.Count
                    })
                    .ToList(); // Perform the formatting in memory

                return reportData;
            }
        }

    }

}

HW03_u20679484/Controllers/BorrowReportController.cs
using HW03_u20679484.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CsvHelper;
using OfficeOpenXml;


namespace HW03_u20679484.Controllers
{
    public class BorrowReportController : Controller
    {
        private LibraryEntities db = new LibraryEntities();
        private BorrowReport borrowReport = new BorrowReport();

        // GET: BorrowReport
        public ActionResult Index()
        {
            var students = db.students.ToList();
            ViewBag.StudentsList = new SelectList(students, "studentId", "name");
            return View("Index");
        }


        [HttpPost]
        public ActionResult GenerateReport(int studentId)
        {
            // Get the student's monthly borrow data
            List<StudentMonthlyBorrow> reportData = borrowReport.GetStudentMonthlyBorrows(studentId);

            return Json(reportData, JsonRequestBehavior.AllowGet);
        }
       

    }
}

HW03_u20679484/Views/BorrowReport/Index.cshtml
@model List<HW03_u20679484.Models.StudentMonthlyBorrow>

@{
    ViewBag.Title = "Monthly Borrow Report";
}

<div class="container">
    <h2>Monthly Borrow Report</h2>
    <p>Select a student to generate the report:</p>

    @using (Html.BeginForm("GenerateReport", "BorrowReport", FormMethod.Post))
    {
        <div class="form-group">
            @Html.DropDownList("studentId", (SelectList)ViewBag.StudentsList, "Select a student", new { @class = "form-control" })
            <button type="submit" class="btn btn-primary">Generate Report</button>
        </div>
    }

    <div class="row">
        <div class="col-md-6">
            <canvas id="columnChart"></canvas>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Data processing code to eliminate duplicate months and aggregate books borrowed
    var reportData = [
        [{ "Month": "12/2015", "BooksBorrowed": 1 }, { "Month": "12/2015", "BooksBorrowed": 1 }, { "Month": "01/2016", "BooksBorrowed": 1 }, { "Month": "02/2016", "BooksBorrowed": 1 }, { "Month": "03/2016", "BooksBorrowed": 1 }, { "Month": "03/2016", "BooksBorrowed": 1 }, { "Month": "04/2016", "BooksBorrowed": 1 }, { "Month": "04/2016", "BooksBorrowed": 1 }, { "Month": "06/2016", "BooksBorrowed": 1 }, { "Month": "08/2016", "BooksBorrowed": 1 }, { "Month": "10/2016", "BooksBorrowed": 1 }, { "Month": "11/2016", "BooksBorrowed": 1 }, { "Month": "12/2016", "BooksBorrowed": 1 }, { "Month": "12/2016", "BooksBorrowed": 1 }, { "Month": "01/2017", "BooksBorrowed": 1 }, { "Month": "01/2017", "BooksBorrowed": 1 }, { "Month": "01/2017", "BooksBorrowed": 1 }, { "Month": "02/2017", "BooksBorrowed": 1 }, { "Month": "03/2017", "BooksBorrowed": 1 }, { "Month": "03/2017", "BooksBorrowed": 1 }]
    ];

    var uniqueLabels = [];
    var dataPoints = [];

    reportData.forEach(function (item) {
        var month = item.Month;
        var booksBorrowed = item.BooksBorrowed;

        var existingMonthIndex = uniqueLabels.indexOf(month);

        if (existingMonthIndex === -1) {
            uniqueLabels.push(month);
            dataPoints.push(booksBorrowed);
        } else {
            dataPoints[existingMonthIndex] += booksBorrowed;
        }
    });

    var ctx = document.getElementById('columnChart').getContext('2d');

    // Create the column chart with unique months and aggregated data
    var chart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: uniqueLabels,
            datasets: [{
                label: 'Books Borrowed',
                data: dataPoints,
                backgroundColor: 'rgba(54, 162, 235, 0.2)',
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true,
                    stepSize: 1
                }
            },
            responsive: true,
            maintainAspectRatio: false
        }
    });
</script>